blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Baca README dulu
    url: https://github.com/makcrtve/geetRPCS#readme
    about: Pastikan kamu sudah baca dokumentasi sebelum membuat issue
  - name: ðŸ’¬ Diskusi
    url: https://github.com/makcrtve/geetRPCS/discussions
    about: Mau ngobrol atau tanya sesuatu? Gunakan Discussions